- hosts: all
  become: true
  become_user: root
  tasks:

    - name: update host file
      lineinfile:
        dest: /etc/hosts
        regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
        state: present
      become: true
      with_items: "{{ groups.all }}"
